// frontend/src/components/ui/AuthorApplicationPage.vue
<template>
  <div class="application-background">
    <v-container class="application-container">
      <div v-if="!isLoggedIn" class="text-center pa-16">
        <p>작가 신청을 위해 **로그인이 필요합니다.**</p>
        <v-btn to="/login" color="primary">로그인 하러 가기</v-btn>
      </div>
      <div v-else-if="isLoading" class="text-center pa-16">
        <v-progress-circular indeterminate color="primary"></v-progress-circular>
        <p class="mt-4">정보를 불러오는 중입니다...</p>
      </div>
      <v-card v-else-if="user" class="application-panel" flat>
        <v-card-text class="pa-md-10 pa-6">
          <div v-if="applicationStatus === 'APPROVED'" class="text-center">
            <v-icon color="success" size="56">mdi-check-decagram</v-icon>
            <h1 class="text-h4 mt-4">작가 승인 완료</h1>
            <p>이제부터 작가로 활동하실 수 있습니다.</p>
            <v-btn class="mt-4" color="primary" @click="resetApplicationStatus">다시 신청하기 (테스트용)</v-btn>
          </div>
          <div v-else-if="applicationStatus === 'PENDING'" class="text-center">
            <v-icon color="info" size="56">mdi-clock-outline</v-icon>
            <h1 class="text-h4 mt-4">검토 중</h1>
            <p>관리자가 신청서를 검토하고 있습니다.</p>
            <p class="mt-2 text-caption">최대 2~3 영업일이 소요될 수 있습니다.</p>
            <v-btn class="mt-4" color="secondary" @click="resetApplicationStatus">상태 초기화 (테스트용)</v-btn>
          </div>
          <div v-else-if="applicationStatus === 'REJECTED'" class="text-center">
            <v-icon color="error" size="56">mdi-close-octagon-outline</v-icon>
            <h1 class="text-h4 mt-4">신청 반려</h1>
            <p>제출하신 신청서가 반려되었습니다. 자세한 내용은 이메일을 확인해주세요.</p>
            <v-btn class="mt-4" color="primary" @click="resetApplicationStatus">다시 신청하기</v-btn>
          </div>
          <div v-else>
            <h1 class="text-h4 font-weight-bold text-center mb-8">작가 등록 신청</h1>
            <v-form @submit.prevent="handleApplicationSubmit">
              <v-row>
                <v-col cols="12" md="6">
                  <v-text-field :model-value="user.name" label="이름" readonly variant="outlined"></v-text-field>
                </v-col>
                <v-col cols="12" md="6">
                  <v-text-field :model-value="user.email" label="이메일" readonly variant="outlined"></v-text-field>
                </v-col>
              </v-row>
              <v-textarea
                v-model="form.introduction"
                label="작가 소개*"
                variant="outlined"
                counter
                maxlength="500"
                :rules="[v => !!v || '작가 소개는 필수입니다.', v => (v && v.length >= 10) || '최소 10자 이상 작성해주세요.']"
              ></v-textarea>
              <v-checkbox
                v-model="form.agreement"
                label="개인 정보 수집 및 이용에 동의합니다."
                :rules="[v => !!v || '동의가 필요합니다.']"
              ></v-checkbox>
              <v-btn type="submit" :loading="isLoading" :disabled="!isFormValid" color="primary" block size="x-large">
                신청하기
              </v-btn>
            </v-form>
          </div>
        </v-card-text>
      </v-card>
      <div v-else class="text-center pa-16">
        <p>사용자 정보를 불러오는 중입니다...</p>
        <v-progress-circular indeterminate color="primary"></v-progress-circular>
      </div>
    </v-container>
    <v-snackbar v-model="snackbar.show" :color="snackbar.color">{{ snackbar.text }}</v-snackbar>
  </div>
</template>

<script>
import { mapState } from 'pinia';
import { useUserStore } from '@/store/userStore'; // 수정된 경로
import { useWriterStore } from '@/store/writerStore'; // 수정된 경로

export default {
  name: 'AuthorApplicationPage',
  data: () => ({
    form: { introduction: '', agreement: false },
    snackbar: { show: false, text: '', color: 'success' },
  }),
  computed: {
    // mapState 헬퍼를 사용하여 스토어 상태를 컴포넌트의 computed 속성으로 매핑합니다.
    ...mapState(useUserStore, ['isLoggedIn', 'currentUser']),
    // currentUser를 user로 별칭 지정 (템플릿에서 user.name 등으로 접근하기 위함)
    user() {
      return this.currentUser;
    },
    ...mapState(useWriterStore, ['applicationStatus', 'isLoading']),
    isFormValid() {
      return this.form.introduction && this.form.introduction.length >= 10 && this.form.agreement;
    },
  },
  methods: {
    async handleApplicationSubmit() {
      if (!this.isFormValid) {
        this.showSnackbar('필수 정보를 모두 입력하고 동의해주세요.', 'warning');
        return;
      }
      const writerStore = useWriterStore();
      try {
        await writerStore.submitApplication({ userId: this.user.id, bio: this.form.introduction });
        this.showSnackbar('작가 신청이 완료되었습니다. 관리자 승인을 기다려주세요.', 'success');
        // 폼 초기화
        this.form.introduction = '';
        this.form.agreement = false;
      } catch (e) {
        this.showSnackbar('작가 신청 중 오류가 발생했습니다. 다시 시도해주세요.', 'error');
        console.error("Submission error:", e);
      }
    },
    showSnackbar(text, color) {
      this.snackbar.text = text;
      this.snackbar.color = color;
      this.snackbar.show = true;
    },
    // 테스트 및 개발을 위한 상태 초기화 메소드
    resetApplicationStatus() {
      const writerStore = useWriterStore();
      writerStore.setApplicationStatus('NONE');
      this.showSnackbar('작가 신청 상태가 초기화되었습니다.', 'info');
    }
  },
  async created() {
    const userStore = useUserStore();
    // 페이지 로드 시 사용자 정보를 먼저 로드합니다.
    await userStore.loadCurrentUser();

    if (this.isLoggedIn && this.user) {
      const writerStore = useWriterStore();
      await writerStore.checkMyApplicationStatus(this.user.id);
    } else if (!this.isLoggedIn) {
      // 로그인되지 않은 경우 스낵바를 통해 안내
      this.showSnackbar('작가 신청은 로그인 후 이용 가능합니다.', 'info');
    }
  },
  // 스토어 상태 변경을 관찰하여 필요한 경우 동작
  watch: {
    isLoggedIn(newVal) {
      if (newVal && this.user) {
        const writerStore = useWriterStore();
        writerStore.checkMyApplicationStatus(this.user.id);
      }
    },
    user(newVal) {
      if (newVal && this.isLoggedIn) {
        const writerStore = useWriterStore();
        writerStore.checkMyApplicationStatus(this.user.id);
      }
    }
  }
};
</script>

<style scoped>
.application-background {
  background: linear-gradient(to right, #ece9e6, #ffffff);
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 20px 0;
}

.application-container {
  max-width: 800px;
}

.application-panel {
  border-radius: 12px;
  box-shadow: 0 8px 25px rgba(0, 0, 0, 0.1);
}
</style>

// frontend/src/writers/AuthorApplicationPage.jsx
// src/pages/AuthorApplicationPage.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../axios';
import './AuthorApplicationPage.css';
import Header from '../mainPage/Header';
import Footer from '../mainPage/Footer';
import { useAuth } from '../contexts/AuthContext'; // 로그인 상태 및 사용자 정보 가져오기

const AuthorApplicationPage = () => {
  const { isLoggedIn, user } = useAuth(); // Context에서 로그인 상태와 사용자 정보 가져옴
  const navigate = useNavigate();

  const [form, setForm] = useState({ introduction: '', agreement: false });
  const [applicationStatus, setApplicationStatus] = useState('NONE'); // NONE, PENDING, APPROVED, REJECTED
  const [isLoading, setIsLoading] = useState(true); // 초기 로딩 상태
  const [submitLoading, setSubmitLoading] = useState(false); // 신청 버튼 로딩 상태
  const [error, setError] = useState('');

  const isFormValid = form.introduction.length >= 20 && form.agreement; // 최소 20자 이상

  useEffect(() => {
    const checkUserAndApplicationStatus = async () => {
      // 1. 로그인 상태 확인
      if (!isLoggedIn || !user || !user.id) {
        alert('작가 신청은 로그인 후 이용 가능합니다.');
        navigate('/login');
        return;
      }

      // 2. 기존 신청 상태 확인
      try {
        const response = await api.get(`/writer-candidates/${user.id}`); // userId로 신청 정보 조회
        if (response.status === 200 && response.data) {
          setApplicationStatus(response.data.status); // PENDING, APPROVED, REJECTED 등
        } else {
          setApplicationStatus('NONE'); // 신청 정보 없음
        }
      } catch (err) {
        if (err.response && err.response.status === 404) {
          setApplicationStatus('NONE'); // 404는 신청 정보가 없다는 의미
        } else {
          console.error('작가 신청 상태 확인 중 오류:', err);
          setError('작가 신청 상태를 불러오는 데 실패했습니다.');
          setApplicationStatus('ERROR'); // 오류 상태
        }
      } finally {
        setIsLoading(false);
      }
    };

    checkUserAndApplicationStatus();
  }, [isLoggedIn, user, navigate]); // user, isLoggedIn 변경 시 다시 확인

  const handleApplicationSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (!isFormValid) {
      setError('작가 소개는 최소 20자 이상 작성해야 하며, 동의가 필요합니다.');
      return;
    }
    if (!user || !user.id || !user.name || !user.email) {
      setError('사용자 정보가 불완전합니다. 다시 로그인해주세요.');
      return;
    }

    setSubmitLoading(true);

    try {
      // API 명세: POST /writers/apply
      const response = await api.post('/writers/apply', {
        userId: user.id,
        bio: form.introduction,
        // name, email은 백엔드에서 userClient.getUser를 통해 가져오므로 프론트에서 보낼 필요 없음
      });

      console.log('작가 신청 완료:', response.data);
      setApplicationStatus(response.data.status); // PENDING 상태로 업데이트될 것임
      alert('작가 신청이 성공적으로 제출되었습니다. 관리자 승인을 기다려주세요.');
      setForm({ introduction: '', agreement: false }); // 폼 초기화

    } catch (err) {
      console.error('작가 신청 실패:', err);
      if (err.response && err.response.status === 409) { // 409 Conflict: 이미 신청된 경우
        setError('이미 작가 신청이 완료되었거나 진행 중입니다.');
        // 상태를 강제로 PENDING으로 업데이트 (이미 신청되어 있을 가능성)
        setApplicationStatus('PENDING');
      } else if (err.response && err.response.data && typeof err.response.data === 'string') {
        setError(`신청 실패: ${err.response.data}`);
      } else if (err.response && err.response.data && err.response.data.message) {
        setError(`신청 실패: ${err.response.data.message}`);
      } else {
        setError('작가 신청 중 오류가 발생했습니다. 다시 시도해주세요.');
      }
    } finally {
      setSubmitLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="application-page-wrapper loading">
        <Header />
        <main className="application-main-content">
          <div className="loading-spinner"></div>
          <p>작가 신청 상태를 불러오는 중...</p>
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="application-page-wrapper">
      <Header />
      <main className="application-main-content">
        <div className="application-container">
          {applicationStatus === 'APPROVED' && (
            <div className="status-message approved">
              <span className="status-icon">✅</span>
              <h1 className="status-title">작가 승인 완료</h1>
              <p>이제부터 작가로 활동하실 수 있습니다. 멋진 작품을 기대합니다!</p>
            </div>
          )}
          {applicationStatus === 'PENDING' && (
            <div className="status-message pending">
              <span className="status-icon">🕒</span>
              <h1 className="status-title">작가 신청 검토 중</h1>
              <p>관리자가 회원님의 신청서를 검토하고 있습니다. 최대 2~3영업일이 소요될 수 있습니다.</p>
            </div>
          )}
          {applicationStatus === 'REJECTED' && (
            <div className="status-message rejected">
              <span className="status-icon">❌</span>
              <h1 className="status-title">작가 신청 반려</h1>
              <p>제출하신 신청서가 반려되었습니다. 자세한 내용은 등록된 이메일로 안내됩니다.</p>
              <button className="reset-button" onClick={() => setApplicationStatus('NONE')}>다시 신청하기</button>
            </div>
          )}
          {applicationStatus === 'ERROR' && (
            <div className="status-message error">
              <span className="status-icon">⚠️</span>
              <h1 className="status-title">오류 발생</h1>
              <p>{error}</p>
              <button className="reset-button" onClick={() => navigate('/')}>메인으로 돌아가기</button>
            </div>
          )}
          {applicationStatus === 'NONE' && (
            <div className="application-form-section">
              <h1 className="auth-title">작가 등록 신청</h1>
              {error && <p className="error-message mb-4">{error}</p>}
              <form onSubmit={handleApplicationSubmit} className="auth-form">
                <div className="form-group">
                  <label>사용자 이름</label>
                  <input type="text" value={user?.name || ''} readOnly disabled />
                </div>
                <div className="form-group">
                  <label>이메일 주소</label>
                  <input type="email" value={user?.email || ''} readOnly disabled />
                </div>
                <div className="form-group">
                  <label htmlFor="introduction">작가 소개 (최소 20자 이상)*</label>
                  <textarea
                    id="introduction"
                    value={form.introduction}
                    onChange={(e) => setForm({ ...form, introduction: e.target.value })}
                    placeholder="작가로서 자신을 소개해주세요. (예: 어떤 분야의 글을 쓰고 싶은지, 경력 등)"
                    rows="8"
                    required
                  ></textarea>
                </div>
                <div className="form-group checkbox-group">
                  <input
                    type="checkbox"
                    id="agreement"
                    checked={form.agreement}
                    onChange={(e) => setForm({ ...form, agreement: e.target.checked })}
                    required
                  />
                  <label htmlFor="agreement">
                    본인은 제공하는 정보가 정확함을 확인하며, AI PUBLISH 작가 활동 약관에 동의합니다.
                  </label>
                </div>
                <button type="submit" className="submit-button" disabled={submitLoading || !isFormValid}>
                  {submitLoading ? '신청 중...' : '신청하기'}
                </button>
              </form>
            </div>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default AuthorApplicationPage;
